## Function makeCacheMatrix takes a matrix as input and generate a list with four 
## functions and a variable m. Function cacheSolve will interact with an object 
## generated by makeCacheMatrix, can compute a given matrix's inverse


## m is used to cache the inverse of a given matrix. By default, m is “NULL”, 
## which means the inverse of a given matrix has not been calculated. 

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
    x<<- y
    m<- NULL
  }
  get <- function() x
  setInverse <- function (Inverse) m <<- Inverse
  getInverse <- function () m
  list (set = set, get = get, setInverse = setInverse, getInverse = getInverse)
  
}


## cacheSolve will first check if m in x, the inverse of a given matrix, is NULL. If it is 
## not, then this implies a calculation has been made before. Therefore, an inverse 
## calculation can be avoided and the function will pull the inverse from m and return the 
## value, minimizing execution time. If the inverse is NULL, cacheSolve will compute the 
## inverse and call setInverse in x and store it in m. 

cacheSolve <- function(x, ...) {
  m <- x$getInverse()
  if ( !is.null(m)) {
    message("getting cache data")
    return(m)
  }
  data<-x$get()
  m<-solve(data,...)
  x$setInverse(m)
  m
  
}

## An example for using this pair of functions 

## y<- matrix(rnorm(250000), ncol=500,nrow=500) ## generate a 500*500 matrix with components drawn from a standard normal distribution
## x<- makeCacheMatrix(y)                       ## generate an object x based on matrix y
## system.time(cacheSolve(x))                   ## This gives the time used for calculating the inverse for x for the first time 
## system.time(cacheSolve(x))                   ## Since an inverse was found in the previous step, this will return the message. Exe time
                                                ## should be very fast. 